#!/bin/bash

declare -a variable=("jetEta" "jetPt" "nTrkAlgo_IP3D" "nTrkAlgo_JF" "nTrkAlgo_SV1" "JFdR" "JFeFc" "JFmVtx" "JFnVtx" "JFsig3d" "SV1dR" "SV1eFc" "SV1mVtx" "SV1nVtx" "SV1sig3d" "bHPt" "bHPtFraction" "bHjetDR")
#declare -a variable=("nTrkAlgo_IP3D")
#collection="EMPFlow"
#collection="VR10Cone"
collection="VR10Ghost"
declare -a bin=("1B" "1D0B" "0B0D" "2B" "2D0B" "2B2D")

for ivar in ${variable[@]};
do 
    for ibin in ${bin[@]};
    do
	root -l -b <<EOF
.x show_variable_inLabelMatrix.C("$collection","$ivar","$ibin") 
.q
EOF
    done
done

