void lxplus_files(TChain *f)
{ 
  /* 
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_001.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_002.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_003.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_004.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_005.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_006.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_007.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_008.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_009.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_010.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_011.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_012.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_013.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_Akt4EMPf_BTagging201903_derorigin_014.root");
  */
    
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_001.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_002.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_003.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_004.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_005.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_006.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_007.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_008.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_009.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_010.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_011.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_012.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_013.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02TrackGhostTagJets_derorigin_014.root");

  /*
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_001.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_002.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_003.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_004.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_005.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_006.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_007.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_008.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_009.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_010.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_011.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_012.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_013.root");
  f->Add("/eos/user/m/mcentonz/File/FTPF/FTPF_taggers_output/QT/flav_AktVR30Rmax4Rmin02Tr_BTagging201903_derorigin_014.root");
  */

}
