{
  float a1=9;
  TCanvas c1("c1", "canvas", 1200, 900);
//  gStyle->SetOptStat(0);
  gStyle->SetPalette(kRainBow);
  TH1F *h1 = new TH1F("h1","A1",100,-a1,a1);
//  h1->SetFillColor(3);
  h1=(TH1F*)trk_d0_BinB->Clone();
  h1->Add(trk_d0_CinB);
  Double_t norm_1 = h1->GetEntries();
  h1->Scale(1/norm_1);
  h1->SetTitle("trk_d0");
  h1->GetXaxis()->SetTitle("d0");
  h1->GetXaxis()->SetRangeUser(-a1,a1);
  h1->SetLineColor(kRed);
  h1->SetLineWidth(3);
  h1->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h1,"reco b/c tracks");
  leg->Draw();

  TCanvas c2("c2", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *h2 = new TH1F("h2","A2",100,-a1,a1);
  h2=(TH1F*)trk_d0_BinB->Clone();
  Double_t norm_2 = h2->GetEntries();
  h2->Scale(1/norm_2);
  h2->SetTitle("trk_d0");
  h2->GetXaxis()->SetTitle("d0");
  h2->GetXaxis()->SetRangeUser(-a1,a1);
  h2->SetLineColor(kGreen);
  h2->SetLineWidth(3);
  h2->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h2,"reco b tracks");
  leg->Draw();

  TCanvas c3("c3", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *h3 = new TH1F("h3","A3",100,-a1,a1);
  h3=(TH1F*)trk_d0_CinB->Clone();
  Double_t norm_3 = h3->GetEntries();
  h3->Scale(1/norm_3);
  h3->SetTitle("trk_d0");
  h3->GetXaxis()->SetTitle("d0");
  h3->GetXaxis()->SetRangeUser(-a1,a1);
  h3->SetLineColor(kOrange);
  h3->SetLineWidth(3);
  h3->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h3,"reco c tracks");
  leg->Draw();

  TCanvas c4("c4", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *h4 = new TH1F("h4","A4",100,-a1,a1);
  h4=(TH1F*)trk_d0_FRAGinB->Clone();
  Double_t norm_4 = h4->GetEntries();
  h4->Scale(1/norm_4);
  h4->SetTitle("trk_d0");
  h4->GetXaxis()->SetTitle("d0");
  h4->GetXaxis()->SetRangeUser(-a1,a1);
  h4->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h4,"reco FRAG tracks");
  leg->Draw();

  TCanvas c5("c5", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *h5 = new TH1F("h5","A5",100,-a1,a1);
  h5=(TH1F*)trk_d0_GEANTinB->Clone();
  Double_t norm_5 = h5->GetEntries();
  h5->Scale(1/norm_5);
  h5->SetTitle("trk_d0");
  h5->GetXaxis()->SetTitle("d0");
  h5->GetXaxis()->SetRangeUser(-a1,a1);
  h5->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h5,"reco GEANT tracks");
  leg->Draw();

  TCanvas c6("c6", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *h6 = new TH1F("h6","A6",100,-a1,a1);
  h6=(TH1F*)trk_d0_PUinB->Clone();
  Double_t norm_6 = h6->GetEntries();
  h6->Scale(1/norm_6);
  h6->SetTitle("trk_d0");
  h6->GetXaxis()->SetTitle("d0");
  h6->GetXaxis()->SetRangeUser(-a1,a1);
  h6->Draw("hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(h6,"reco PU tracks");
  leg->Draw();


  TCanvas cc("cc", "canvas", 1200, 900);
  gStyle->SetOptStat(0);
//  gStyle->SetPalette(kRainBow);
  TH1F *hc = new TH1F("hc","Ac",100,-15,15);
  hc=(TH1F*)trk_d0_BinB->Clone();
  Double_t norm_c = hc->GetEntries();
  hc->Scale(1/norm_c);
  TH1F *hc2 = new TH1F("hc2","Ac2",100,-15,15);
  hc2=(TH1F*)trk_d0_CinB->Clone();
  Double_t norm_c2 = hc2->GetEntries();
  hc2->Scale(1/norm_c2);
//  hc->SetMarkerStyle(kFullSquare);
//  hc2->SetMarkerStyle(kFullTriangleUp);
  hc2->GetXaxis()->SetTitle("d0");
  hc2->GetXaxis()->SetRangeUser(-15, 15);
  hc->SetLineColor(kRed);
  hc->SetLineWidth(3);
  hc2->SetLineColor(kBlue);
  hc2->SetLineWidth(3);
  hc->Draw("hist");
  hc2->Draw("same hist");
  leg = new TLegend(0.6,0.8,0.9,0.9);
  leg->AddEntry(hc,"reco b tracks");
  leg->AddEntry(hc2,"reco c tracks");
  leg->Draw();


//leg = new TLegend(0.6,0.8,0.9,0.9);
//leg->AddEntry("reco b traks","reco c tracks");

}
